steps:
- name: 'cirrusci/flutter:stable'
  entrypoint: bash
  #args: ['flutter', 'build', 'appbundle', '&&', 'cp', 'build/app/outputs/bundle/release/app.aab', '/workspace/driver.aab']
  args:
  - '-c'
  - |
    flutter build appbundle --no-sound-null-safety 
    cp build/app/outputs/bundle/release/app-release.aab /workspace/user.aab
timeout: 1800s
options:
 machineType: 'E2_HIGHCPU_8'
artifacts:
  objects:
    location: 'gs://shikilia-appbundles/'
    paths: ['/workspace/user.aab']